#!/bin/bash

echo "This program depicts how to declare a variable and then demonstrates the use of if else conditional statement"
n=10
if [ $n -lt 10 ];
then
        echo "It is a one digit number"
else
        echo "It is a two digit number"
fi
